### ISSUE TITLE
New module description

### ISSUE THREAD

**Issue by ymdahi** [learnfullabs/h5p-xapi#1]
## Overview

- xAPI is a way to collect data about a student's interaction: https://xapi.com/overview/
- H5P is a tool that lets instructors build interactive learning activities: https://h5p.org/
- H5P emmits xAPI whenever a student is interacting with an activity: https://h5p.org/documentation/x-api

## To test h5p xapi:

1. Go to: https://studio.camerisefsl.ca/h5p/94/embed
2. Open the browser console
3. Add the following to the console: `H5P.externalDispatcher.on('xAPI', function (event) {  console.log(event.data.statement);});`
4. Start interacting with the activity

You will notice xAPI statements for all interactions. Specifically you may notice the statements that track score/grade.

here's an example

```
{
    "actor": {
        "name": "testmod",
        "mbox": "mailto:email@email.com",
        "objectType": "Agent"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/answered",
        "display": {
            "en-US": "answered"
        }
    },
    "object": {
        "id": "https://studio.camerisefsl.ca/h5p/94/embed?subContentId=e288f7f4-701f-43f2-a370-55ff80b3eab5",
        "objectType": "Activity",
        "definition": {
            "extensions": {
                "http://h5p.org/x-api/h5p-local-content-id": 94,
                "http://h5p.org/x-api/h5p-subContentId": "e288f7f4-701f-43f2-a370-55ff80b3eab5"
            },
            "name": {
                "en-US": "Sans titre Drag the Words"
            },
            "interactionType": "fill-in",
            "type": "http://adlnet.gov/expapi/activities/cmi.interaction",
            "description": {
                "en-US": "Déplacez les textes dans les emplacements qui leur correspondent.<br/>Presque. Il a marché 4,95 kilomètres, donc __________ cinq kilomètres."
            },
            "correctResponsesPattern": [
                "à peu près"
            ]
        }
    },
    "context": {
        "contextActivities": {
            "parent": [
                {
                    "id": "https://studio.camerisefsl.ca/h5p/94/embed",
                    "objectType": "Activity"
                }
            ],
            "category": [
                {
                    "id": "http://h5p.org/libraries/H5P.DragText-1.10",
                    "objectType": "Activity"
                }
            ]
        }
    },
    "result": {
        "response": "à propos",
        "score": {
            "min": 0,
            "raw": 0,
            "max": 1,
            "scaled": 0
        },
        "duration": "PT3.27S",
        "completion": true
    }
}
```

## Goal

We want to create a new module that **saves all xAPI statements into a Database**. Specifically, this module should

- [x] #2
- [x] Create relationships to the data, including:
  - [x] add the user id of the user who is interacting with the activity
  - [x] add the user id of the user who owns the node
- [x] Generate a View so that each h5p node has "statistics" and "grades"
- [x] Only the owner of the node should be able to view statistics for their h5p node.
- [x] The student should only be able to see their own statistics for any node they have interacted with.

## Other details

- Refer to h5p.api.php: https://git.drupalcode.org/project/h5p/blob/HEAD/h5p.api.php
- Refer to existing h5p customization module for ideas: https://github.com/ymdahi/h5p_css_overrides

**Comment by danrod96** [comment]
I've created a basic view that displays the raw Event JSON data: https://dev-studio.camerisefsl.ca/h5p-xpi/rawdata?page=0

I am working on a few other views that displays statistics, grades and results.

**Comment by danrod96** [comment]
I've implemented a view with results: https://dev-studio.camerisefsl.ca/h5p-xpi/event-result-data/
This view takes two arguments, uid and node id (of the H5P Resource),
For example for viewing the interactions that the admin did with the H5P Resource 1, you can go to:
https://dev-studio.camerisefsl.ca/h5p-xpi/event-result-data/1/1
For viewing the interactions that I did (User Id 3) with the same node:
https://dev-studio.camerisefsl.ca/h5p-xpi/event-result-data/3/1

This view only displays results for the user who interacted with the H5P resource and for the Resource's node, and for admin users too.

The view can use some makeup (TRUE or FALSE instead or 1 or 0, format date) I can work on this later.

There's also some helper views that can be used for debugging purposes (only admins can open that url):

https://dev-studio.camerisefsl.ca/h5p-xpi/event-actor-data
https://dev-studio.camerisefsl.ca/h5p-xpi/event-context-data
https://dev-studio.camerisefsl.ca/h5p-xpi/event-object-data
https://dev-studio.camerisefsl.ca/h5p-xpi/rawdata

These views can use some makeup too (I can work on this later)

Sorry for the late closing on this ticket (got trapped with some personal issues) feel free to reopen this if needed, I'll do some testing and I'll pass onto the gutenberg module.
